### ISSUE TITLE
Topic is not creating

### ISSUE THREAD

**Issue by sreenivasulu-paruchuri** [blacktop/docker-kafka-alpine#9]
I am using blacktop/kafka in my gitlab-ci.yml for testing kafka for my project. Upto blacktop/kafka:2.6 i am able to create topics but as 3.0 is released, now topics are not creating, could you please guide me 

Below are the variables i used in my .gitlab-ci.yml file

`  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,INTERNAL://localhost:9093'
  KAFKA_BROKER_ID: '1'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
  KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_CREATE_TOPICS: "test_topic:1:1"`

**Comment by pmorelli92** [comment]
@blacktop I am also running the same issue:

```
version: "3.8"
services:
  kafka:
    image: blacktop/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CREATE_TOPICS=vault.api.v1.workflows.workflow_instance.create.requests:1:1
```

Can you shed some light?
